
package br.com.unitri.posjava.trabalhofinal.soap.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClienteWSImplService", targetNamespace = "http://ws.soap.trabalhofinal.posjava.unitri.com.br/", wsdlLocation = "http://localhost:8080/webservice-soap/services/ClienteSOAPWS?wsdl")
public class ClienteWSImplService
    extends Service
{

    private final static URL CLIENTEWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTEWSIMPLSERVICE_EXCEPTION;
    private final static QName CLIENTEWSIMPLSERVICE_QNAME = new QName("http://ws.soap.trabalhofinal.posjava.unitri.com.br/", "ClienteWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservice-soap/services/ClienteSOAPWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTEWSIMPLSERVICE_WSDL_LOCATION = url;
        CLIENTEWSIMPLSERVICE_EXCEPTION = e;
    }

    public ClienteWSImplService() {
        super(__getWsdlLocation(), CLIENTEWSIMPLSERVICE_QNAME);
    }

    public ClienteWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTEWSIMPLSERVICE_QNAME, features);
    }

    public ClienteWSImplService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTEWSIMPLSERVICE_QNAME);
    }

    public ClienteWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTEWSIMPLSERVICE_QNAME, features);
    }

    public ClienteWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClienteWS
     */
    @WebEndpoint(name = "ClienteWSImplPort")
    public ClienteWS getClienteWSImplPort() {
        return super.getPort(new QName("http://ws.soap.trabalhofinal.posjava.unitri.com.br/", "ClienteWSImplPort"), ClienteWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteWS
     */
    @WebEndpoint(name = "ClienteWSImplPort")
    public ClienteWS getClienteWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soap.trabalhofinal.posjava.unitri.com.br/", "ClienteWSImplPort"), ClienteWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTEWSIMPLSERVICE_EXCEPTION!= null) {
            throw CLIENTEWSIMPLSERVICE_EXCEPTION;
        }
        return CLIENTEWSIMPLSERVICE_WSDL_LOCATION;
    }

}
