
package br.com.unitri.posjava.trabalhofinal.soap.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClienteWS", targetNamespace = "http://ws.soap.trabalhofinal.posjava.unitri.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClienteWS {


    /**
     * 
     * @return
     *     returns java.util.List<br.com.unitri.posjava.trabalhofinal.soap.ws.Cliente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listar", targetNamespace = "http://ws.soap.trabalhofinal.posjava.unitri.com.br/", className = "br.com.unitri.posjava.trabalhofinal.soap.ws.Listar")
    @ResponseWrapper(localName = "listarResponse", targetNamespace = "http://ws.soap.trabalhofinal.posjava.unitri.com.br/", className = "br.com.unitri.posjava.trabalhofinal.soap.ws.ListarResponse")
    public List<Cliente> listar();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salvar", targetNamespace = "http://ws.soap.trabalhofinal.posjava.unitri.com.br/", className = "br.com.unitri.posjava.trabalhofinal.soap.ws.Salvar")
    @ResponseWrapper(localName = "salvarResponse", targetNamespace = "http://ws.soap.trabalhofinal.posjava.unitri.com.br/", className = "br.com.unitri.posjava.trabalhofinal.soap.ws.SalvarResponse")
    public void salvar(
        @WebParam(name = "arg0", targetNamespace = "")
        Cliente arg0);

}
