
package br.com.unitri.posjava.contatosw.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContatosWS", targetNamespace = "http://ws.contatosw.posjava.unitri.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContatosWS {


    /**
     * 
     * @return
     *     returns java.util.List<br.com.unitri.posjava.contatosw.ws.Contato>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaContatos", targetNamespace = "http://ws.contatosw.posjava.unitri.com.br/", className = "br.com.unitri.posjava.contatosw.ws.ListaContatos")
    @ResponseWrapper(localName = "listaContatosResponse", targetNamespace = "http://ws.contatosw.posjava.unitri.com.br/", className = "br.com.unitri.posjava.contatosw.ws.ListaContatosResponse")
    public List<Contato> listaContatos();

}
