
package br.com.unitri.posjava.contatosw.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContatoWSImplService", targetNamespace = "http://ws.contatosw.posjava.unitri.com.br/", 
wsdlLocation = "http://localhost:8081/wsdlnovo.xml")
public class ContatoWSImplService
    extends Service
{

    private final static URL CONTATOWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTATOWSIMPLSERVICE_EXCEPTION;
    private final static QName CONTATOWSIMPLSERVICE_QNAME = new QName("http://ws.contatosw.posjava.unitri.com.br/", "ContatoWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/wsdlnovo.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTATOWSIMPLSERVICE_WSDL_LOCATION = url;
        CONTATOWSIMPLSERVICE_EXCEPTION = e;
    }

    public ContatoWSImplService() {
        super(__getWsdlLocation(), CONTATOWSIMPLSERVICE_QNAME);
    }

    public ContatoWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTATOWSIMPLSERVICE_QNAME, features);
    }

    public ContatoWSImplService(URL wsdlLocation) {
        super(wsdlLocation, CONTATOWSIMPLSERVICE_QNAME);
    }

    public ContatoWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTATOWSIMPLSERVICE_QNAME, features);
    }

    public ContatoWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContatoWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContatosWS
     */
    @WebEndpoint(name = "ContatoWSImplPort")
    public ContatosWS getContatoWSImplPort() {
        return super.getPort(new QName("http://ws.contatosw.posjava.unitri.com.br/", "ContatoWSImplPort"), ContatosWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContatosWS
     */
    @WebEndpoint(name = "ContatoWSImplPort")
    public ContatosWS getContatoWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.contatosw.posjava.unitri.com.br/", "ContatoWSImplPort"), ContatosWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTATOWSIMPLSERVICE_EXCEPTION!= null) {
            throw CONTATOWSIMPLSERVICE_EXCEPTION;
        }
        return CONTATOWSIMPLSERVICE_WSDL_LOCATION;
    }

}
